# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-TypeKey-Sign
version:      0.07
version_from: lib/Authen/TypeKey/Sign.pm
installdirs:  site
requires:
    Class::ErrorHandler:           0
    Crypt::DSA:                    0
    Crypt::DSA::Key:               0
    Crypt::DSA::Signature:         0
    Getopt::Long:                  2.33
    Math::Pari:                    0
    MIME::Base64:                  0
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
